apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # App services addresses
  GATEWAY_ADDR: ":8080" # Gateway ‡∏¢‡∏±‡∏á‡∏Ñ‡∏á‡∏ü‡∏±‡∏á‡∏ó‡∏µ‡πà port 8080 (‡∏≠‡∏±‡∏ô‡∏ô‡∏µ‡πâ‡∏ñ‡∏π‡∏Å‡πÅ‡∏•‡πâ‡∏ß)
  
  # 
  # üëá [‡πÅ‡∏Å‡πâ‡πÑ‡∏Ç‡∏ï‡∏£‡∏á‡∏ô‡∏µ‡πâ]
  # ‡πÄ‡∏õ‡∏•‡∏µ‡πà‡∏¢‡∏ô‡∏à‡∏≤‡∏Å localhost (:) ‡πÑ‡∏õ‡πÄ‡∏õ‡πá‡∏ô‡∏ä‡∏∑‡πà‡∏≠ Service
  #
  USER_ADDR: "user-service-svc:8081"
  CHAT_ADDR: "chat-service-svc:8082"         # (‡πÄ‡∏ï‡∏£‡∏µ‡∏¢‡∏°‡πÑ‡∏ß‡πâ‡∏™‡∏≥‡∏´‡∏£‡∏±‡∏ö chat)
  NOTI_ADDR: "notification-service-svc:8083" # (‡πÄ‡∏ï‡∏£‡∏µ‡∏¢‡∏°‡πÑ‡∏ß‡πâ‡∏™‡∏≥‡∏´‡∏£‡∏±‡∏ö noti)
  EVENT_ADDR: "event-service-svc:8084"       # (‡πÄ‡∏ï‡∏£‡∏µ‡∏¢‡∏°‡πÑ‡∏ß‡πâ‡∏™‡∏≥‡∏´‡∏£‡∏±‡∏ö event)
  ORGANIZER_ADDR: "organizer-service-svc:8085" # (‡πÄ‡∏ï‡∏£‡∏µ‡∏¢‡∏°‡πÑ‡∏ß‡πâ‡∏™‡∏≥‡∏´‡∏£‡∏±‡∏ö organizer)

  # Database Name
  DATABASE_NAME: "user-db"