apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  # ---------------------------------
  # üëá DSN ‡∏ó‡∏µ‡πà‡πÅ‡∏Å‡πâ‡πÑ‡∏Ç‡∏™‡∏≥‡∏´‡∏£‡∏±‡∏ö Kubernetes
  # ---------------------------------
  DATABASE_DSN: "host=postgres-svc user=newuser password=newpassword dbname=user-db port=5432 sslmode=disable"
  
  # ---------------------------------
  # (Secret ‡∏≠‡∏∑‡πà‡∏ô‡πÜ ‡∏à‡∏≤‡∏Å .env ‡∏Ç‡∏≠‡∏á‡∏Ñ‡∏∏‡∏ì)
  # ---------------------------------
  RABBITMQ_URI: "amqps://nsemvrni:JFrEKtzZLj9jmmwXKZ_VSNZoP5M6u8ON@gorilla.lmq.cloudamqp.com/nsemvrni"
  JWT_SECRET: "shinnynig"
  EMAIL: "pukkomobbcheese@gmail.com"
  EMAIL_PW: "tsvw rngv btxe igor"