# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  # Port ‡∏Ç‡∏≠‡∏á API Gateway
  - containerPort: 30080 # üëà 1. ‡∏ô‡∏µ‡πà‡∏Ñ‡∏∑‡∏≠ NodePort (‡∏ï‡πâ‡∏≠‡∏á 30k+)
    hostPort: 8080       # üëà 2. ‡∏ô‡∏µ‡πà‡∏Ñ‡∏∑‡∏≠ localhost ‡∏Ç‡∏≠‡∏á‡∏Ñ‡∏∏‡∏ì (‡∏ï‡∏±‡πâ‡∏á‡πÄ‡∏õ‡πá‡∏ô 8080 ‡πÑ‡∏î‡πâ)
  
  # (Port ‡∏Ç‡∏≠‡∏á pgAdmin ‡πÅ‡∏•‡∏∞ Postgres ‡∏Å‡πá‡∏ï‡∏±‡πâ‡∏á hostPort ‡πÄ‡∏õ‡πá‡∏ô 5051 ‡πÅ‡∏•‡∏∞ 5433 ‡πÑ‡∏î‡πâ‡πÄ‡∏ä‡πà‡∏ô‡∏Å‡∏±‡∏ô)
  - containerPort: 30051
    hostPort: 5051
  - containerPort: 30033
    hostPort: 5433