apiVersion: v1
kind: Service
metadata:
  name: user-service-svc # üëà ‡∏ô‡∏µ‡πà‡∏Ñ‡∏∑‡∏≠ "‡∏ä‡∏∑‡πà‡∏≠" ‡∏´‡∏£‡∏∑‡∏≠ "‡∏ó‡∏µ‡πà‡∏≠‡∏¢‡∏π‡πà" ‡πÉ‡∏´‡∏°‡πà
spec:
  # 
  # type: ClusterIP (‡∏ô‡∏µ‡πà‡∏Ñ‡∏∑‡∏≠ default)
  # ‡∏´‡∏°‡∏≤‡∏¢‡∏Ñ‡∏ß‡∏≤‡∏°‡∏ß‡πà‡∏≤ Service ‡∏ô‡∏µ‡πâ‡∏à‡∏∞‡πÄ‡∏Ç‡πâ‡∏≤‡∏ñ‡∏∂‡∏á‡πÑ‡∏î‡πâ‡∏à‡∏≤‡∏Å "‡∏†‡∏≤‡∏¢‡πÉ‡∏ô" cluster ‡πÄ‡∏ó‡πà‡∏≤‡∏ô‡∏±‡πâ‡∏ô
  #
  selector:
    app: user-service # üëà ‡∏ä‡∏µ‡πâ‡πÑ‡∏õ‡∏ó‡∏µ‡πà Pod ‡∏ó‡∏µ‡πà‡∏°‡∏µ label 'app: user-service'
  ports:
  - protocol: TCP
    port: 8081        # üëà Port ‡∏ó‡∏µ‡πà Service ‡∏ô‡∏µ‡πâ‡∏à‡∏∞‡∏£‡∏±‡∏ö‡∏ü‡∏±‡∏á
    targetPort: 8081  # üëà Port ‡∏ó‡∏µ‡πà Container (Pod) ‡πÄ‡∏õ‡∏¥‡∏î‡∏£‡∏≠